### ISSUE TITLE
GPIO 14 bootstrap should be LOW but it is shown as HIGH in datasheet

### ISSUE THREAD

**Issue by valentt** [8devices/carambola2#48]
I have looked at your datasheet and it shows that GPIO 14 should be HIGH during bootstrap - ![selection_025](https://cloud.githubusercontent.com/assets/620901/5590629/aace8158-913a-11e4-8a2f-c914fd8d138b.png)

But in Carambola 2 dev board both GPIO 13 and 14 (ETH0 and ETH1 LEDs) are connected to GND (LOW) - ![selection_024](https://cloud.githubusercontent.com/assets/620901/5590634/dacad578-913a-11e4-8515-3bac100a987e.png)

Could you explain this discrepancy or correct Carambola 2 datasheet so that GPIO 14 is labeled LOW instead HIGH.

**Comment by valentt** [comment]
Do you need any aditional info from me?

**Comment by GiedriusM** [comment]
Carambola2 modules have internal 10k pull-up/down resistors. GPIO14 bootstrap should be LOW, so no problems here. GPIO13 should be HIGH and due to voltage drop on the LED it is "high enough" at about 1.8V.

If this answers your question, please close the issue and next time for non-software problems please use the forums.

**Comment by valentt** [comment]
@GiedriusM thanks for quick reply. 

> Carambola2 modules have internal 10k pull-up/down resistors.
Are they programmable or fixed? Do GPIO 13 and 14 have internal pull-up or pull-down resistors and can that be changed?

> GPIO14 bootstrap should be LOW, so no problems here.
Agreed.

> GPIO13 should be HIGH and due to voltage drop on the LED it is "high enough" at about 1.8V.
Ok, this part confuses me. I see that both GPIO 13 and 14 are wired the same, and that they both are connected over LED to GND. So how is that one is Bootstap High and other Low? Do they have different internal pull-up and pull-down resistors? Any explanation would be really helpful. Thanks.

**Comment by GiedriusM** [comment]
1) They are physical (external) resistors. I don't remember whether GPIO13 and 14 have programmable internal resistors, but it is irrelevant in this case, because configuration could only be done after the bootstrapping stage.

3) In the reference GPIO13 and 14 are wired the same OUTSIDE of the module, but they have different wiring INSIDE the module (under the metal shielding). GPIO14 is connected to GND via 10k resistor (inside) and to GND via LED and 330Ohm resistor (outside), which results in overall pull to GND. GPIO13 is connected to Vcc via 10k resistor (inside) and to GND via LED and 330Ohm resistors (outside). That forms a non-linear resistor divider, which at low Vcc voltages outputs voltage approximately that of forward diode voltage drop. Yellow LEDs have a typical voltage drop of 1.8.-2.2V and that's what can be measured on GPIO13 when the chip is in reset state.

**Comment by valentt** [comment]
Thanks

**Comment by valentt** [comment]
This info you gave is great and really helpful. I work for one German company developing new medical device based on Carambola 2. I must admit that this is the first time our team got any valuable information regarding hardware. Previously we tried using forums and direct email but answers were on the level of first-level support team and they didn't understand our questions, replies they gave could be described as "have you tried turning it off and on again?" :(

If you @GiedriusM are available as to be hired directly for some questions our company is willing to pay 8Devices or to you directly for your future service.

Unfortunately Carambola 2 datasheet [1] is really really insufficient for developing devices based on it. We got stuck numerous times. So managers are deciding now to switch to any other platform on which we can get (payed) support and better documentation. This is the last chance to stay with Carambola 2 and keep using it for further product development.

I'm amazed what contributors to OpenWrt did with documenting devices like WR703N [2] from TPLINK, and all by reverse-engineering [3]. I have been trying to document Carambola 2 [4] as best I can by using what they have learned from WR703N and by using our own knowledge and your (really thin) documentation.

[1]  http://www.8devices.com/media/files/Carambola2.pdf
[2] http://wiki.openwrt.org/toh/tp-link/tl-wr703n
[3] https://squonk42.github.io/TL-WR703N/
[4] http://wiki.openwrt.org/toh/8devices/carambola2
