### ISSUE TITLE
Request: "USB Periphetial Controller" Driver for Gadget

### ISSUE THREAD

**Issue by adamheinrich** [8devices/carambola2#6]
Hello, forum post advices to use GitHub for requests too.

I would really love to use Carambola2's USB port with the Gadget framework to make it act as USB ethernet device. I would be nice for some configuration (Wi-Fi parameters especially) of small device because RJ45 connectors are quite big and the USB port has to be there for charging.

But there is no "USB Periphetial Controller" for AR9331 listed in "kernel_menuconfig" menu. Could you please add this driver?

Thank you very much!

Adam

**Comment by mantas-p** [comment]
Closing this old issue

**Comment by gergamel** [comment]
Any chance we could reopen this issue? I am trying to get the Carambola2 to act as a device (rather than a host). I have strapped GPIO13 low, and have enabled kmod-usb-gadget support in the build (for usb-eth-gadget), but it looks like the ath79/dev-usb driver is entirely host oriented (e.g. it sets qca_force_host_mode = 1, amongst other issues).

Does anyone know what might need to be done here to enable device mode? I've tried setting qca_force_host_mode to 0, but a quick skim of the dev-usb.c suggests there is more to it than that. Possibly the driver needs a bit of a rewrite, but I'm not sure where to start.

**Comment by mantas-p** [comment]
Hi,

AFAIK driver that supports AR9331 in USB device mode is not currently in openwrt source tree.
You can find correct driver here:
https://github.com/mirror/dd-wrt/blob/master/src/linux/universal/linux-3.5/drivers/usb/gadget/ath_udc.c

Also you may need to add pull-up resistors according to USB standard to get Carambola2 detected as device.
